#列的映射
class DataConfig:
    case_id ="用例ID"
    case_module = "模块"
    api_name = "接口名称"
    url = "URL"
    pre_exec = "前置条件"
    method = "请求类型"
    para_type = "参数类型"
    params = "请求参数"
    expect_result = "预期结果"
    actual_result = "实际结果"
    remark = "备注"
    is_run = "是否运行"
    headers = "headers"
    cookies = "cookies"
    status_code = "status_code"
    db_assert = "数据库验证"